///* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
#include "E:/Program/Java/jdk-18.0.2/include/jni.h"
#include "E:/Program/Java/jdk-18.0.2/include/win32/jni_md.h"
#include<CL/cl.h>
using namespace std;

/* Header for class cn_mingbai_ScreenInMC_Natives_GPUDither */

#ifndef _Included_cn_mingbai_ScreenInMC_Natives_GPUDither
#define _Included_cn_mingbai_ScreenInMC_Natives_GPUDither
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_mingbai_ScreenInMC_Natives_GPUDither
 * Method:    dither
 * Signature: ([I[III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_mingbai_ScreenInMC_Natives_GPUDither_dither
  (JNIEnv *, jclass, jintArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
bool getPlatforms(cl_uint* count, cl_platform_id** result);
bool getPlatformNames(cl_uint* count, char*** names);
bool init();
bool dither(const int* image, const int* palette, int paletteColorCount, const int width, const int height, short* result);