download-browser-core:
  github-proxy: "https://ghproxy.com/%URL%" #留空为不使用Github代理
  http-proxy: "" #留空为不使用http代理 例: http://127.0.0.1:1080
  jcef-download-url:
    type: 1 #0:直接下载文件(仅支持.tar.gz)(须手动选择对应系统) 1:下载Github仓库Releases文件(自动选择系统)
    url: "https://github.com/jcefmaven/jcefbuild"
    system-type: "" #仅在type为1时生效 可设置为: linux-amd64, linux-arm, linux-arm64, macosx-amd64, macosx-arm64, windows-amd64, windows-arm64,windows-i386 留空为自动获取
    version: "" #仅在type为1时生效 JCEF版本号(Tags) 留空为自动获取 最新JCEF已不支持32位Linux，需使用1.0.26版本
jcef-extra-args: ""
jcef-transparent: false
jcef-enable-gpu: false
browser-main-page: "https://bing.com/"
language: "zh_cn" #支持zh_cn en_us qps_ploc zh_tw zh_hk
opencl-device: -3 #-4=Java快速运算 -3=自动选择 -2=Java运算 -1=C++运算 0+=OpenCL设备 (-4,-2,-1均不支持更换分块大小)
piece-size: 4 #分块大小 可设置 1(关闭抖色) 2 4 8 16
render-distance-limit: 32 #显示器最小距离(超过该距离将不向玩家发送显示器内容) 单位: 方块
default-fps-limit: 18 #默认fps限制(仅对带帧率限制功能的核心起作用)
default-font: "" #默认字体设置(若为空则使用系统默认字体)