# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build ScreenInMC Plugin 1.19.2

on:
  push:
   branches: [ "master" ]
  pull_request:
   branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: Vampire/setup-wsl@v2
        with:
            distribution: Ubuntu-22.04
            use-cache: 'true'
      - shell: wsl-bash_Ubuntu-22.04 {0}
        name: Setup Linux
        run: |
            sudo dpkg --add-architecture i386
            sudo apt-get -y update
            sudo apt-get install --no-upgrade -y ocl-icd-opencl-dev ocl-icd-opencl-dev:i386 opencl-headers opencl-headers:i386 opencl-dev opencl-dev:i386 cmake gcc-multilib g++-multilib build-essential openjdk-17-jdk
      - uses: robinraju/release-downloader@v1.8
        with:
          repository: "KhronosGroup/OpenCL-SDK"
          latest: true
          fileName: "OpenCL-SDK-*Win*.zip"
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
      - name: Build CPP Bridge
        run: |
          mv OpenCL-SDK-*Win*.zip src/main/cpp/
          cd src/main/cpp/
          $env:JAVA_PATH = ((Get-Command java).Path | Split-Path -Parent | Split-Path -Parent)
          Expand-Archive OpenCL-SDK-*Win-x86.zip -DestinationPath "X86" 
          Expand-Archive OpenCL-SDK-*Win-x64.zip -DestinationPath "X64" 
          cd .\X86\
          Move-Item * OpenCL
          cd ..\X64\
          Move-Item * OpenCL
          cd ..
          $env:OpenCL86 = ((Resolve-Path(".\X86\OpenCL\lib\")).Path+"OpenCL.lib")
          $env:OpenCL64 = ((Resolve-Path(".\X64\OpenCL\lib\")).Path+"OpenCL.lib")
          $env:OpenCLPath = (Resolve-Path(".\X64\OpenCL\include\")).Path
          ./build-all-github.ps1
      - name: Get latest commit hash
        id: latest_commit
        run: |
          $url = "https://hub.spigotmc.org/stash/scm/spigot/spigot.git"
          $hash = git ls-remote $url HEAD | foreach { $_.Split()[0] }
          echo "::set-output name=hash::$hash"
      - name: Cache Spigot
        id: cache-spigot
        uses: actions/cache@v3
        env:
          cache-name: cache-spigot-files
        with:
          path: ~/.m2
          key: 1.19.2-${{ steps.latest_commit.outputs.hash }}
      - if: ${{ steps.cache-spigot.outputs.cache-hit != 'true' }}
        name: Build Spigot
        run: |
          mkdir BuildTools
          cd BuildTools
          C:\msys64\usr\bin\wget.exe "https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar"
          java -jar BuildTools.jar --rev 1.19.2 --remapped
          cd ..
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
          gradle-version: '7.5.1'
      - name: Make Jar File with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: jar
          gradle-version: '7.5.1'
      - name: Remapping Jar File
        run: |
          New-Item -ItemType Directory -Path build/libs/remapped/ -Force
          C:\msys64\usr\bin\wget.exe "https://repo.maven.apache.org/maven2/net/md-5/SpecialSource/1.11.0/SpecialSource-1.11.0-shaded.jar" -O "$HOME\.m2\repository\net\md-5\SpecialSource\1.11.0\SpecialSource-1.11.0-shaded.jar"
          java -cp "$HOME\.m2\repository\net\md-5\SpecialSource\1.11.0\SpecialSource-1.11.0-shaded.jar;$HOME\.m2\repository\org\spigotmc\spigot\1.19.2-R0.1-SNAPSHOT\spigot-1.19.2-R0.1-SNAPSHOT-remapped-mojang.jar" net.md_5.specialsource.SpecialSource --live -i build\libs\ScreenInMC.jar -o build\libs\ScreenInMC-obf.jar -m $HOME\.m2\repository\org\spigotmc\minecraft-server\1.19.2-R0.1-SNAPSHOT\minecraft-server-1.19.2-R0.1-SNAPSHOT-maps-mojang.txt --reverse
          java -cp "$HOME\.m2\repository\net\md-5\SpecialSource\1.11.0\SpecialSource-1.11.0-shaded.jar;$HOME\.m2\repository\org\spigotmc\spigot\1.19.2-R0.1-SNAPSHOT\spigot-1.19.2-R0.1-SNAPSHOT-remapped-obf.jar" net.md_5.specialsource.SpecialSource --live -i build\libs\ScreenInMC-obf.jar -o build\libs\remapped\ScreenInMC.jar -m $HOME\.m2\repository\org\spigotmc\minecraft-server\1.19.2-R0.1-SNAPSHOT\minecraft-server-1.19.2-R0.1-SNAPSHOT-maps-spigot.csrg
      - name: Upload Plugin Jar File
        uses: actions/upload-artifact@master
        with:
          name: ScreenInMC
          path: build/libs/remapped/
#     - name: Delete workflow runs
#       uses: Mattraks/delete-workflow-runs@v2.0.3
#       with:
#         token: ${{ github.token }}
#         repository: ${{ github.repository }}
#         retain_days: 1
#         keep_minimum_runs: 1
#     - name: Upload Spigot Jar File
#       uses: actions/upload-artifact@master
#       with:
#         name: Spigot-1.19.2
#         path: BuildTools/spigot-*.jar
